version: '3'

services:
  ema_aubergine_api:
    env_file:
      - .env
    depends_on:
      - ema_aubergine_database
    links:
      - ema_aubergine_database
    build:
      context: ./api
    container_name: ema_aubergine_api
    restart: always
    volumes:
      - ./api/src:/app
      - .env:/.env

    ports:
      - ${API_PORT}:80
    networks:
      - ema_aubergine

  ema_aubergine_web:
    env_file:
      - .env
    depends_on:
      - ema_aubergine_database
    links:
      - ema_aubergine_database
    build:
      context: ./web
    container_name: ema_aubergine_web
    restart: always
    volumes:
      - ./web/app/:/app/

    ports:
      - ${WEB_PORT}:3000
    networks:
      - ema_aubergine

  ema_aubergine_database:
    env_file:
      - .env
    image: 'mariadb:latest'
    container_name: ema_aubergine_database
    restart: always
    environment:
      - MYSQL_DATABASE=${SQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${SQL_ROOTPASSWORD}
    volumes:
      - ${SQL_DATA_PATH}:/var/lib/mysql/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ema_aubergine
    hostname: aubergines_database

  ema_aubergine_phpmyadmin:
    env_file:
      - .env
    image: phpmyadmin/phpmyadmin
    container_name: ema_aubergine_phpmyadmin
    restart: always
    depends_on:
      - ema_aubergine_database
    links:
      - ema_aubergine_database
    environment:
      PMA_HOST: ema_aubergine_database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - ema_aubergine
    ports:
      - ${PMA_PORT}:80


networks:
  ema_aubergine: